# This defines the colors of the webpage

[theme]
base="light"
primaryColor="#0072CE"                     # e.g. colour for buttons and sliders
backgroundColor="#ffffff"
secondaryBackgroundColor="#e8eef9"                      # e.g. colour of sidebar
textColor="#000000"
font="sans serif"
